### ISSUE TITLE
GoDockerJobProxy 

### ISSUE THREAD

**Issue by pbelmann** [BiBiServ/jobproxy#102]
[GoDocker](http://www.genouest.org/godocker/) 

> it acts as an additional layer above those tools on multiple user systems where users do not have Docker priviledges or knowledge.

web api:

http://go-docker-web.readthedocs.io/en/latest/views.html

**Comment by mwiens** [comment]
Closing, since it does not satisfy our needs in security due to a forced need of a world-read-writable shared volume. So godocker can be used only in __closed__ cloud environments with no additional system users.
