### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by pbelmann** [BiBiServ/jobproxy#114]
A command should be a string array not just a string.

**Comment by mwiens** [comment]
@pbelmann so each entry represents a part of the command e.g. parameter flag / value?

**Comment by pbelmann** [comment]
Yes e.g.: ["/bin/echo", "Hello World"] this is default for docker, kubernetes and other frameworks

**Comment by mwiens** [comment]
closed by #122

**Comment by pbelmann** [comment]
Thx @mwiens
