### ISSUE TITLE
Maven Enforcer Plugin

### ISSUE THREAD

**Issue by pbelmann** [BiBiServ/jobproxy#69]
I think we should include the [Maven Enforcer Plugin](https://maven.apache.org/enforcer/maven-enforcer-plugin/). It will help us to avoid issues like #66 .
Especially the rules:

* dependencyConvergence - ensure all dependencies converge to the same version.
 
* requireMavenVersion - enforces the Maven version.

But also other rules could be useful:

https://maven.apache.org/enforcer/enforcer-rules/index.html

**Comment by jkrue** [comment]
Sounds good, we should include the plugin asap.
